feat(minio): add expiration rules

diff --git a/utils/senders/minio-sender b/utils/senders/minio-sender
--- a/utils/senders/minio-sender
+++ b/utils/senders/minio-sender
@@ -5,6 +5,8 @@ set -e -o pipefail
 FILENAME="$1"
 REMOTE_PATH="$2"
 MINIO_API_VERSION="${MINIO_API_VERSION:-S3v4}"
+RETENTION="${MINIO_RETENTION:-30d}"
+
 
 source .colors
 
@@ -17,6 +19,20 @@ mc -q --insecure alias set pg "$MINIO_SERVER" "$MINIO_ACCESS_KEY" "$MINIO_SECRET
 
 clr_blue clr_bright "> mc cp -r $FILENAME $REMOTE_PATH"
 
-mc -q --insecure cp -r "$FILENAME" "$REMOTE_PATH"  || { echo "Backup failed"; mc rm "$REMOTE_PATH"; exit 1; }
+mc -q --insecure cp -r "$FILENAME" "$REMOTE_PATH" || { echo "Backup failed"; mc rm "$REMOTE_PATH"; exit 1; }
+
+
+clr_blue clr_bright "Checking if Expiration rule is set"
+prefix=$(basename "$REMOTE_PATH")
+bucket=$(dirname "$REMOTE_PATH")
+rule_exist=$(mc ilm rule ls "$REMOTE_PATH" --json | jq  ".config.Rules[] | select(.Filter.Prefix==\"$prefix\")") || true
+
+if [ -z "$rule_exist" ]
+then
+    clr_blue "Creating Expiration Rule";
+    mc ilm rule add "$REMOTE_PATH"  --expire-days "30";
+else
+    clr_blue "Expiration Rule Already exist";
+fi
 
 clr_blue "Upload Complete"
